kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.service_name }}-secrets
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $val := .Values.secret_data }}   # secret_data must be a key/value content defined in values.yaml.gotmpl
  {{ $key }}: {{ $val | quote }}
  {{- end}}
type: Opaque
