# generated by fastapi-codegen:
#   filename:  oas3.json
#   timestamp: 2023-02-23T17:05:57+00:00

# pylint: skip-file
from __future__ import annotations

from typing import Optional

from fastapi import APIRouter, FastAPI, Path, Query

from app.schemas.entity import (
    Content,
    Content1,
    Content2,
    Content3,
    Content4,
    Content5,
    Content6,
    Content7,
    Content8,
    Content9,
    Content10,
    Content11,
    Content12,
    Content13,
    Content14,
    Content15,
    Content16,
    Content17,
    Content18,
    Content19,
    Content20,
    Content21,
    Content22,
    Content23,
    Content24,
    Content25,
    Content26,
    Content27,
    Content28,
    Content29,
    Content30,
    Content31,
    Content32,
    Content33,
    Content34,
    Content35,
    Content36,
    Content37,
    Content38,
    Content39,
    Content40,
    Content41,
    Data,
    DataDiscoveryModuleInternalDiscoveryScheduler,
    DataDiscoveryModuleInternalDiscoverySchedulerBusIds,
    DataDiscoveryModuleInternalDiscoverySchedulerFrequency,
    DataDiscoveryModuleInternalDiscoverySchedulerPost,
    DataDiscoveryModuleInternalDiscoverySchedulerSchdeuler,
    DataDiscoveryModuleInternalDiscoverySchedulerSchdeulercreatedtime,
    DataDiscoveryModuleInternalDiscoverySchedulerStatus,
    DataDiscoveryModuleInternalMessageBuses,
    DataDiscoveryModuleInternalMessageBusesBusesBusesId,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettings,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKerberosServiceName,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKeyPassword,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKeystoreLocation,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKeystorePassword,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsPassword,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsPost,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsPrincipal,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsSaslMechanism,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsSecProtocol,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsTokenEndpoint,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsUsername,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdCreaterdby,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdHost,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdId,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdInstanceType,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdPort,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistry,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryPort,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryPost,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryUrl,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryVersion,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdTimestamp,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsId,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdId,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdSchema,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdTopic,
    DataDiscoveryModuleInternalMessageBusesBusesBusesIdVersion,
    DataDiscoveryModuleInternalMessageBusesPost,
    DataDiscoveryModuleInternalSchemasInfo,
    DataDiscoveryModuleInternalSchemasInfoPost,
    DataDiscoveryModuleInternalSchemasInfoSchemasSchemasId,
    DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdDefinition,
    DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdId,
    DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdRevisionCreateTime,
    DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdRevisionId,
    DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdSchema,
    DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdType,
    DataPost,
    DataPutPatch,
    Insert1,
    Insert3,
    Insert5,
    WithDefaults1,
    WithDefaults2,
    WithDefaults4,
    WithDefaults5,
    WithDefaults7,
    WithDefaults8,
    WithDefaults10,
    WithDefaults11,
    WithDefaults13,
    WithDefaults14,
    WithDefaults16,
    WithDefaults17,
    WithDefaults19,
    WithDefaults20,
    WithDefaults22,
    WithDefaults23,
    WithDefaults25,
    WithDefaults26,
    WithDefaults28,
    WithDefaults29,
    WithDefaults31,
    WithDefaults32,
    WithDefaults34,
    WithDefaults35,
    WithDefaults37,
    WithDefaults38,
    WithDefaults40,
    WithDefaults41,
    WithDefaults43,
    WithDefaults44,
    WithDefaults46,
    WithDefaults47,
    WithDefaults49,
    WithDefaults50,
    WithDefaults52,
    WithDefaults53,
    WithDefaults55,
    WithDefaults56,
    WithDefaults58,
    WithDefaults59,
    WithDefaults61,
    WithDefaults62,
    WithDefaults64,
    WithDefaults65,
    WithDefaults67,
    WithDefaults68,
    WithDefaults70,
    WithDefaults71,
    WithDefaults73,
    WithDefaults74,
    WithDefaults76,
    WithDefaults77,
    WithDefaults79,
    WithDefaults80,
    WithDefaults82,
    WithDefaults83,
    WithDefaults85,
    WithDefaults86,
    WithDefaults88,
    WithDefaults89,
    WithDefaults91,
    WithDefaults92,
    WithDefaults94,
    WithDefaults95,
    WithDefaults97,
    WithDefaults98,
    WithDefaults100,
    WithDefaults101,
    WithDefaults103,
    WithDefaults104,
    WithDefaults106,
    WithDefaults107,
    WithDefaults109,
    WithDefaults110,
    WithDefaults112,
    WithDefaults113,
    WithDefaults115,
    WithDefaults116,
    WithDefaults118,
    WithDefaults119,
    WithDefaults121,
    WithDefaults122,
    WithDefaults124,
    WithDefaults125,
)

router = APIRouter()


@router.get('/data', response_model=Data)
async def data_get() -> Data:
    """
        ['']
        This YANG module has been created for the purpose of the message-bus onboard entity.
    It defines the model for onboarding a discovery-module-internal to TINAA ecosystem
    """
    pass


@router.post('/data', response_model=None)
async def data_post(
    body: DataPost,
) -> None:
    """
        ['body: DataPost']
        This YANG module has been created for the purpose of the message-bus onboard entity.
    It defines the model for onboarding a discovery-module-internal to TINAA ecosystem
    """
    pass


@router.put('/data', response_model=None)
async def data_put(
    body: DataPutPatch,
) -> None:
    """
        ['body: DataPutPatch']
        This YANG module has been created for the purpose of the message-bus onboard entity.
    It defines the model for onboarding a discovery-module-internal to TINAA ecosystem
    """
    pass


@router.patch('/data', response_model=None)
async def data_patch(
    body: DataPutPatch,
) -> None:
    """
        ['body: DataPutPatch']
        This YANG module has been created for the purpose of the message-bus onboard entity.
    It defines the model for onboarding a discovery-module-internal to TINAA ecosystem
    """
    pass


@router.get(
    '/data/discovery-module-internal:discovery-scheduler',
    response_model=DataDiscoveryModuleInternalDiscoveryScheduler,
)
async def data_discovery_module_internal_discovery_scheduler_get(
    content: Optional[Content36] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults110] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalDiscoveryScheduler:
    pass


@router.post('/data/discovery-module-internal:discovery-scheduler', response_model=None)
async def data_discovery_module_internal_discovery_scheduler_post(
    body: DataDiscoveryModuleInternalDiscoverySchedulerPost,
) -> None:
    pass


@router.put('/data/discovery-module-internal:discovery-scheduler', response_model=None)
async def data_discovery_module_internal_discovery_scheduler_put(
    body: DataDiscoveryModuleInternalDiscoveryScheduler,
) -> None:
    pass


@router.patch(
    '/data/discovery-module-internal:discovery-scheduler', response_model=None
)
async def data_discovery_module_internal_discovery_scheduler_patch(
    body: DataDiscoveryModuleInternalDiscoveryScheduler,
) -> None:
    pass


@router.delete(
    '/data/discovery-module-internal:discovery-scheduler', response_model=None
)
async def data_discovery_module_internal_discovery_scheduler_delete() -> None:
    pass


@router.get(
    '/data/discovery-module-internal:discovery-scheduler/bus_ids',
    response_model=DataDiscoveryModuleInternalDiscoverySchedulerBusIds,
)
async def data_discovery_module_internal_discovery_scheduler_bus_ids_get(
    content: Optional[Content38] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults116] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalDiscoverySchedulerBusIds:
    """
    ["content: Optional[Content38] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults116] = Query('report-all'", " alias='with-defaults')"]
    List of bus id's to configure in a interval. Example value: [1,2,3,5]
    """
    pass


@router.put(
    '/data/discovery-module-internal:discovery-scheduler/bus_ids', response_model=None
)
async def data_discovery_module_internal_discovery_scheduler_bus_ids_put(
    body: DataDiscoveryModuleInternalDiscoverySchedulerBusIds,
) -> None:
    """
    ['body: DataDiscoveryModuleInternalDiscoverySchedulerBusIds']
    List of bus id's to configure in a interval. Example value: [1,2,3,5]
    """
    pass


@router.patch(
    '/data/discovery-module-internal:discovery-scheduler/bus_ids', response_model=None
)
async def data_discovery_module_internal_discovery_scheduler_bus_ids_patch(
    body: DataDiscoveryModuleInternalDiscoverySchedulerBusIds,
) -> None:
    """
    ['body: DataDiscoveryModuleInternalDiscoverySchedulerBusIds']
    List of bus id's to configure in a interval. Example value: [1,2,3,5]
    """
    pass


@router.delete(
    '/data/discovery-module-internal:discovery-scheduler/bus_ids', response_model=None
)
async def data_discovery_module_internal_discovery_scheduler_bus_ids_delete() -> None:
    """
    ['']
    List of bus id's to configure in a interval. Example value: [1,2,3,5]
    """
    pass


@router.get(
    '/data/discovery-module-internal:discovery-scheduler/frequency',
    response_model=DataDiscoveryModuleInternalDiscoverySchedulerFrequency,
)
async def data_discovery_module_internal_discovery_scheduler_frequency_get(
    content: Optional[Content40] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults122] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalDiscoverySchedulerFrequency:
    """
    ["content: Optional[Content40] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults122] = Query('report-all'", " alias='with-defaults')"]
    Discovery schdeuler frequency. Example value: 14:15:20:05:00:00
    """
    pass


@router.put(
    '/data/discovery-module-internal:discovery-scheduler/frequency', response_model=None
)
async def data_discovery_module_internal_discovery_scheduler_frequency_put(
    body: DataDiscoveryModuleInternalDiscoverySchedulerFrequency,
) -> None:
    """
    ['body: DataDiscoveryModuleInternalDiscoverySchedulerFrequency']
    Discovery schdeuler frequency. Example value: 14:15:20:05:00:00
    """
    pass


@router.patch(
    '/data/discovery-module-internal:discovery-scheduler/frequency', response_model=None
)
async def data_discovery_module_internal_discovery_scheduler_frequency_patch(
    body: DataDiscoveryModuleInternalDiscoverySchedulerFrequency,
) -> None:
    """
    ['body: DataDiscoveryModuleInternalDiscoverySchedulerFrequency']
    Discovery schdeuler frequency. Example value: 14:15:20:05:00:00
    """
    pass


@router.delete(
    '/data/discovery-module-internal:discovery-scheduler/frequency', response_model=None
)
async def data_discovery_module_internal_discovery_scheduler_frequency_delete() -> None:
    """
    ['']
    Discovery schdeuler frequency. Example value: 14:15:20:05:00:00
    """
    pass


@router.get(
    '/data/discovery-module-internal:discovery-scheduler/schdeuler',
    response_model=DataDiscoveryModuleInternalDiscoverySchedulerSchdeuler,
)
async def data_discovery_module_internal_discovery_scheduler_schdeuler_get(
    content: Optional[Content37] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults113] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalDiscoverySchedulerSchdeuler:
    """
    ["content: Optional[Content37] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults113] = Query('report-all'", " alias='with-defaults')"]
    ID of the discovery scheduler
    """
    pass


@router.put(
    '/data/discovery-module-internal:discovery-scheduler/schdeuler', response_model=None
)
async def data_discovery_module_internal_discovery_scheduler_schdeuler_put(
    body: DataDiscoveryModuleInternalDiscoverySchedulerSchdeuler,
) -> None:
    """
    ['body: DataDiscoveryModuleInternalDiscoverySchedulerSchdeuler']
    ID of the discovery scheduler
    """
    pass


@router.patch(
    '/data/discovery-module-internal:discovery-scheduler/schdeuler', response_model=None
)
async def data_discovery_module_internal_discovery_scheduler_schdeuler_patch(
    body: DataDiscoveryModuleInternalDiscoverySchedulerSchdeuler,
) -> None:
    """
    ['body: DataDiscoveryModuleInternalDiscoverySchedulerSchdeuler']
    ID of the discovery scheduler
    """
    pass


@router.delete(
    '/data/discovery-module-internal:discovery-scheduler/schdeuler', response_model=None
)
async def data_discovery_module_internal_discovery_scheduler_schdeuler_delete() -> None:
    """
    ['']
    ID of the discovery scheduler
    """
    pass


@router.get(
    '/data/discovery-module-internal:discovery-scheduler/schdeulercreatedtime',
    response_model=DataDiscoveryModuleInternalDiscoverySchedulerSchdeulercreatedtime,
)
async def data_discovery_module_internal_discovery_scheduler_schdeulercreatedtime_get(
    content: Optional[Content41] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults125] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalDiscoverySchedulerSchdeulercreatedtime:
    """
    ["content: Optional[Content41] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults125] = Query('report-all'", " alias='with-defaults')"]
    Discovery schdeuler created time
    """
    pass


@router.put(
    '/data/discovery-module-internal:discovery-scheduler/schdeulercreatedtime',
    response_model=None,
)
async def data_discovery_module_internal_discovery_scheduler_schdeulercreatedtime_put(
    body: DataDiscoveryModuleInternalDiscoverySchedulerSchdeulercreatedtime,
) -> None:
    """
    ['body: DataDiscoveryModuleInternalDiscoverySchedulerSchdeulercreatedtime']
    Discovery schdeuler created time
    """
    pass


@router.patch(
    '/data/discovery-module-internal:discovery-scheduler/schdeulercreatedtime',
    response_model=None,
)
async def data_discovery_module_internal_discovery_scheduler_schdeulercreatedtime_patch(
    body: DataDiscoveryModuleInternalDiscoverySchedulerSchdeulercreatedtime,
) -> None:
    """
    ['body: DataDiscoveryModuleInternalDiscoverySchedulerSchdeulercreatedtime']
    Discovery schdeuler created time
    """
    pass


@router.delete(
    '/data/discovery-module-internal:discovery-scheduler/schdeulercreatedtime',
    response_model=None,
)
async def data_discovery_module_internal_discovery_scheduler_schdeulercreatedtime_delete() -> None:
    """
    ['']
    Discovery schdeuler created time
    """
    pass


@router.get(
    '/data/discovery-module-internal:discovery-scheduler/status',
    response_model=DataDiscoveryModuleInternalDiscoverySchedulerStatus,
)
async def data_discovery_module_internal_discovery_scheduler_status_get(
    content: Optional[Content39] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults119] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalDiscoverySchedulerStatus:
    """
    ["content: Optional[Content39] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults119] = Query('report-all'", " alias='with-defaults')"]
    Discovery schdeuler status. Example value: Active
    """
    pass


@router.put(
    '/data/discovery-module-internal:discovery-scheduler/status', response_model=None
)
async def data_discovery_module_internal_discovery_scheduler_status_put(
    body: DataDiscoveryModuleInternalDiscoverySchedulerStatus,
) -> None:
    """
    ['body: DataDiscoveryModuleInternalDiscoverySchedulerStatus']
    Discovery schdeuler status. Example value: Active
    """
    pass


@router.patch(
    '/data/discovery-module-internal:discovery-scheduler/status', response_model=None
)
async def data_discovery_module_internal_discovery_scheduler_status_patch(
    body: DataDiscoveryModuleInternalDiscoverySchedulerStatus,
) -> None:
    """
    ['body: DataDiscoveryModuleInternalDiscoverySchedulerStatus']
    Discovery schdeuler status. Example value: Active
    """
    pass


@router.delete(
    '/data/discovery-module-internal:discovery-scheduler/status', response_model=None
)
async def data_discovery_module_internal_discovery_scheduler_status_delete() -> None:
    """
    ['']
    Discovery schdeuler status. Example value: Active
    """
    pass


@router.get(
    '/data/discovery-module-internal:message-buses',
    response_model=DataDiscoveryModuleInternalMessageBuses,
)
async def data_discovery_module_internal_message_buses_get(
    content: Optional[Content] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults2] = Query('report-all', alias='with-defaults'),
) -> DataDiscoveryModuleInternalMessageBuses:
    pass


@router.post('/data/discovery-module-internal:message-buses', response_model=None)
async def data_discovery_module_internal_message_buses_post(
    body: DataDiscoveryModuleInternalMessageBusesPost,
) -> None:
    pass


@router.put('/data/discovery-module-internal:message-buses', response_model=None)
async def data_discovery_module_internal_message_buses_put(
    body: DataDiscoveryModuleInternalMessageBuses,
) -> None:
    pass


@router.patch('/data/discovery-module-internal:message-buses', response_model=None)
async def data_discovery_module_internal_message_buses_patch(
    body: DataDiscoveryModuleInternalMessageBuses,
) -> None:
    pass


@router.delete('/data/discovery-module-internal:message-buses', response_model=None)
async def data_discovery_module_internal_message_buses_delete() -> None:
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesId,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content1] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults5] = Query('report-all', alias='with-defaults'),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesId:
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesId,
    buses_id: str = Path(..., alias='buses-id'),
    insert: Optional[Insert1] = 'first',
    point: Optional[str] = None,
) -> None:
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesId = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettings,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content7] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults23] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettings:
    pass


@router.post(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_post(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsPost = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettings = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettings = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/kerberosServiceName',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKerberosServiceName,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_kerberos_service_name_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content13] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults41] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKerberosServiceName:
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/kerberosServiceName',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_kerberos_service_name_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKerberosServiceName = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/kerberosServiceName',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_kerberos_service_name_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKerberosServiceName = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/kerberosServiceName',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_kerberos_service_name_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/keyPassword',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKeyPassword,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_key_password_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content12] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults38] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKeyPassword:
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/keyPassword',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_key_password_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKeyPassword = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/keyPassword',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_key_password_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKeyPassword = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/keyPassword',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_key_password_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/keystoreLocation',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKeystoreLocation,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_keystore_location_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content10] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults32] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKeystoreLocation:
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/keystoreLocation',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_keystore_location_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKeystoreLocation = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/keystoreLocation',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_keystore_location_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKeystoreLocation = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/keystoreLocation',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_keystore_location_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/keystorePassword',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKeystorePassword,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_keystore_password_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content11] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults35] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKeystorePassword:
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/keystorePassword',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_keystore_password_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKeystorePassword = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/keystorePassword',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_keystore_password_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsKeystorePassword = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/keystorePassword',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_keystore_password_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/password',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsPassword,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_password_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content16] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults50] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsPassword:
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/password',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_password_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsPassword = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/password',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_password_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsPassword = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/password',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_password_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/principal',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsPrincipal,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_principal_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content14] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults44] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsPrincipal:
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/principal',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_principal_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsPrincipal = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/principal',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_principal_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsPrincipal = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/principal',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_principal_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/saslMechanism',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsSaslMechanism,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_sasl_mechanism_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content9] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults29] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsSaslMechanism:
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/saslMechanism',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_sasl_mechanism_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsSaslMechanism = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/saslMechanism',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_sasl_mechanism_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsSaslMechanism = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/saslMechanism',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_sasl_mechanism_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/secProtocol',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsSecProtocol,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_sec_protocol_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content8] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults26] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsSecProtocol:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", " content: Optional[Content8] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults26] = Query('report-all'", " alias='with-defaults')"]
    message bus instance auth protocol: PlAINTEXT/OAUTHBEARER/SCRAM/GSSAPI/kerberos/SASL/SSL/LDAP/keycloak
    """
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/secProtocol',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_sec_protocol_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsSecProtocol = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsSecProtocol = ...']
    message bus instance auth protocol: PlAINTEXT/OAUTHBEARER/SCRAM/GSSAPI/kerberos/SASL/SSL/LDAP/keycloak
    """
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/secProtocol',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_sec_protocol_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsSecProtocol = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsSecProtocol = ...']
    message bus instance auth protocol: PlAINTEXT/OAUTHBEARER/SCRAM/GSSAPI/kerberos/SASL/SSL/LDAP/keycloak
    """
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/secProtocol',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_sec_protocol_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')"]
    message bus instance auth protocol: PlAINTEXT/OAUTHBEARER/SCRAM/GSSAPI/kerberos/SASL/SSL/LDAP/keycloak
    """
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/tokenEndpoint',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsTokenEndpoint,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_token_endpoint_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content17] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults53] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsTokenEndpoint:
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/tokenEndpoint',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_token_endpoint_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsTokenEndpoint = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/tokenEndpoint',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_token_endpoint_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsTokenEndpoint = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/tokenEndpoint',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_token_endpoint_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/username',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsUsername,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_username_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content15] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults47] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsUsername:
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/username',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_username_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsUsername = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/username',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_username_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdAuthSettingsUsername = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/authSettings/username',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_auth_settings_username_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/createrdby',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdCreaterdby,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_createrdby_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content18] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults56] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdCreaterdby:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", " content: Optional[Content18] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults56] = Query('report-all'", " alias='with-defaults')"]
    message bus creatred by user
    """
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/createrdby',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_createrdby_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdCreaterdby = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdCreaterdby = ...']
    message bus creatred by user
    """
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/createrdby',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_createrdby_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdCreaterdby = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdCreaterdby = ...']
    message bus creatred by user
    """
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/createrdby',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_createrdby_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')"]
    message bus creatred by user
    """
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/host',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdHost,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_host_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content4] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults14] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdHost:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", " content: Optional[Content4] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults14] = Query('report-all'", " alias='with-defaults')"]
    message bus host name
    """
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/host',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_host_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdHost = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdHost = ...']
    message bus host name
    """
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/host',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_host_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdHost = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdHost = ...']
    message bus host name
    """
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/host',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_host_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')"]
    message bus host name
    """
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/id',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdId,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_id_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content2] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults8] = Query('report-all', alias='with-defaults'),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdId:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", " content: Optional[Content2] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults8] = Query('report-all'", " alias='with-defaults')"]
    message bus id
    """
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/id',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_id_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdId = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdId = ...']
    message bus id
    """
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/id',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_id_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdId = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdId = ...']
    message bus id
    """
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/id',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_id_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')"]
    message bus id
    """
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/instanceType',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdInstanceType,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_instance_type_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content3] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults11] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdInstanceType:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", " content: Optional[Content3] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults11] = Query('report-all'", " alias='with-defaults')"]
    message bus type. Example Kafka or RabbitMQ
    """
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/instanceType',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_instance_type_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdInstanceType = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdInstanceType = ...']
    message bus type. Example Kafka or RabbitMQ
    """
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/instanceType',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_instance_type_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdInstanceType = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdInstanceType = ...']
    message bus type. Example Kafka or RabbitMQ
    """
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/instanceType',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_instance_type_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')"]
    message bus type. Example Kafka or RabbitMQ
    """
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/port',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdPort,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_port_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content5] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults17] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdPort:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", " content: Optional[Content5] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults17] = Query('report-all'", " alias='with-defaults')"]
    message bus instance port. Example value: 9092
    """
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/port',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_port_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdPort = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdPort = ...']
    message bus instance port. Example value: 9092
    """
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/port',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_port_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdPort = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdPort = ...']
    message bus instance port. Example value: 9092
    """
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/port',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_port_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')"]
    message bus instance port. Example value: 9092
    """
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/schema-registry',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistry,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_schema_registry_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content24] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults74] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistry:
    pass


@router.post(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/schema-registry',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_schema_registry_post(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryPost = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/schema-registry',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_schema_registry_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistry = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/schema-registry',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_schema_registry_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistry = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/schema-registry',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_schema_registry_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/schema-registry/Port',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryPort,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_schema_registry__port_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content26] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults80] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryPort:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", " content: Optional[Content26] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults80] = Query('report-all'", " alias='with-defaults')"]
    message bus instance port. Example value: 9092
    """
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/schema-registry/Port',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_schema_registry__port_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryPort = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryPort = ...']
    message bus instance port. Example value: 9092
    """
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/schema-registry/Port',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_schema_registry__port_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryPort = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryPort = ...']
    message bus instance port. Example value: 9092
    """
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/schema-registry/Port',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_schema_registry__port_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')"]
    message bus instance port. Example value: 9092
    """
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/schema-registry/url',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryUrl,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_schema_registry_url_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content25] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults77] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryUrl:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", " content: Optional[Content25] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults77] = Query('report-all'", " alias='with-defaults')"]
    schema registry url
    """
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/schema-registry/url',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_schema_registry_url_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryUrl = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryUrl = ...']
    schema registry url
    """
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/schema-registry/url',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_schema_registry_url_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryUrl = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryUrl = ...']
    schema registry url
    """
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/schema-registry/url',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_schema_registry_url_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')"]
    schema registry url
    """
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/schema-registry/version',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryVersion,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_schema_registry_version_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content27] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults83] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryVersion:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", " content: Optional[Content27] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults83] = Query('report-all'", " alias='with-defaults')"]
    message bus instance version. Example value: 3.3
    """
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/schema-registry/version',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_schema_registry_version_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryVersion = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryVersion = ...']
    message bus instance version. Example value: 3.3
    """
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/schema-registry/version',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_schema_registry_version_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryVersion = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdSchemaRegistryVersion = ...']
    message bus instance version. Example value: 3.3
    """
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/schema-registry/version',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_schema_registry_version_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')"]
    message bus instance version. Example value: 3.3
    """
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/timestamp',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdTimestamp,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_timestamp_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content19] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults59] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdTimestamp:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", " content: Optional[Content19] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults59] = Query('report-all'", " alias='with-defaults')"]
    message bus created time
    """
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/timestamp',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_timestamp_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdTimestamp = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdTimestamp = ...']
    message bus created time
    """
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/timestamp',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_timestamp_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdTimestamp = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdTimestamp = ...']
    message bus created time
    """
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/timestamp',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_timestamp_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')"]
    message bus created time
    """
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/topics={topics_id}',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsId,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_topics_topics_id_get(
    buses_id: str = Path(..., alias='buses-id'),
    topics_id: str = Path(..., alias='topics-id'),
    content: Optional[Content20] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults62] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsId:
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/topics={topics_id}',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_topics_topics_id_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsId,
    buses_id: str = Path(..., alias='buses-id'),
    topics_id: str = Path(..., alias='topics-id'),
    insert: Optional[Insert3] = 'first',
    point: Optional[str] = None,
) -> None:
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/topics={topics_id}',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_topics_topics_id_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsId = ...,
    buses_id: str = Path(..., alias='buses-id'),
    topics_id: str = Path(..., alias='topics-id'),
) -> None:
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/topics={topics_id}',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_topics_topics_id_delete(
    buses_id: str = Path(..., alias='buses-id'),
    topics_id: str = Path(..., alias='topics-id'),
) -> None:
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/topics={topics_id}/id',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdId,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_topics_topics_id_id_get(
    buses_id: str = Path(..., alias='buses-id'),
    topics_id: str = Path(..., alias='topics-id'),
    content: Optional[Content21] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults65] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdId:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' topics_id: str = Path(...', " alias='topics-id')", " content: Optional[Content21] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults65] = Query('report-all'", " alias='with-defaults')"]
    topic id
    """
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/topics={topics_id}/id',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_topics_topics_id_id_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdId = ...,
    buses_id: str = Path(..., alias='buses-id'),
    topics_id: str = Path(..., alias='topics-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' topics_id: str = Path(...', " alias='topics-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdId = ...']
    topic id
    """
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/topics={topics_id}/id',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_topics_topics_id_id_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdId = ...,
    buses_id: str = Path(..., alias='buses-id'),
    topics_id: str = Path(..., alias='topics-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' topics_id: str = Path(...', " alias='topics-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdId = ...']
    topic id
    """
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/topics={topics_id}/id',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_topics_topics_id_id_delete(
    buses_id: str = Path(..., alias='buses-id'),
    topics_id: str = Path(..., alias='topics-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' topics_id: str = Path(...', " alias='topics-id')"]
    topic id
    """
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/topics={topics_id}/schema',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdSchema,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_topics_topics_id_schema_get(
    buses_id: str = Path(..., alias='buses-id'),
    topics_id: str = Path(..., alias='topics-id'),
    content: Optional[Content23] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults71] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdSchema:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' topics_id: str = Path(...', " alias='topics-id')", " content: Optional[Content23] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults71] = Query('report-all'", " alias='with-defaults')"]
     schema name
    """
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/topics={topics_id}/schema',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_topics_topics_id_schema_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdSchema = ...,
    buses_id: str = Path(..., alias='buses-id'),
    topics_id: str = Path(..., alias='topics-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' topics_id: str = Path(...', " alias='topics-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdSchema = ...']
     schema name
    """
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/topics={topics_id}/schema',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_topics_topics_id_schema_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdSchema = ...,
    buses_id: str = Path(..., alias='buses-id'),
    topics_id: str = Path(..., alias='topics-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' topics_id: str = Path(...', " alias='topics-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdSchema = ...']
     schema name
    """
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/topics={topics_id}/schema',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_topics_topics_id_schema_delete(
    buses_id: str = Path(..., alias='buses-id'),
    topics_id: str = Path(..., alias='topics-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' topics_id: str = Path(...', " alias='topics-id')"]
     schema name
    """
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/topics={topics_id}/topic',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdTopic,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_topics_topics_id_topic_get(
    buses_id: str = Path(..., alias='buses-id'),
    topics_id: str = Path(..., alias='topics-id'),
    content: Optional[Content22] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults68] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdTopic:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' topics_id: str = Path(...', " alias='topics-id')", " content: Optional[Content22] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults68] = Query('report-all'", " alias='with-defaults')"]
    topic name
    """
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/topics={topics_id}/topic',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_topics_topics_id_topic_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdTopic = ...,
    buses_id: str = Path(..., alias='buses-id'),
    topics_id: str = Path(..., alias='topics-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' topics_id: str = Path(...', " alias='topics-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdTopic = ...']
    topic name
    """
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/topics={topics_id}/topic',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_topics_topics_id_topic_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdTopic = ...,
    buses_id: str = Path(..., alias='buses-id'),
    topics_id: str = Path(..., alias='topics-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' topics_id: str = Path(...', " alias='topics-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdTopicsTopicsIdTopic = ...']
    topic name
    """
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/topics={topics_id}/topic',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_topics_topics_id_topic_delete(
    buses_id: str = Path(..., alias='buses-id'),
    topics_id: str = Path(..., alias='topics-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' topics_id: str = Path(...', " alias='topics-id')"]
    topic name
    """
    pass


@router.get(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/version',
    response_model=DataDiscoveryModuleInternalMessageBusesBusesBusesIdVersion,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_version_get(
    buses_id: str = Path(..., alias='buses-id'),
    content: Optional[Content6] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults20] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalMessageBusesBusesBusesIdVersion:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", " content: Optional[Content6] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults20] = Query('report-all'", " alias='with-defaults')"]
    message bus instance version. Example value: 3.3
    """
    pass


@router.put(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/version',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_version_put(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdVersion = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdVersion = ...']
    message bus instance version. Example value: 3.3
    """
    pass


@router.patch(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/version',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_version_patch(
    body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdVersion = ...,
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')", ' body: DataDiscoveryModuleInternalMessageBusesBusesBusesIdVersion = ...']
    message bus instance version. Example value: 3.3
    """
    pass


@router.delete(
    '/data/discovery-module-internal:message-buses/buses={buses_id}/version',
    response_model=None,
)
async def data_discovery_module_internal_message_buses_buses_buses_id_version_delete(
    buses_id: str = Path(..., alias='buses-id'),
) -> None:
    """
    ['buses_id: str = Path(...', " alias='buses-id')"]
    message bus instance version. Example value: 3.3
    """
    pass


@router.get(
    '/data/discovery-module-internal:schemas-info',
    response_model=DataDiscoveryModuleInternalSchemasInfo,
)
async def data_discovery_module_internal_schemas_info_get(
    content: Optional[Content28] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults86] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalSchemasInfo:
    pass


@router.post('/data/discovery-module-internal:schemas-info', response_model=None)
async def data_discovery_module_internal_schemas_info_post(
    body: DataDiscoveryModuleInternalSchemasInfoPost,
) -> None:
    pass


@router.put('/data/discovery-module-internal:schemas-info', response_model=None)
async def data_discovery_module_internal_schemas_info_put(
    body: DataDiscoveryModuleInternalSchemasInfo,
) -> None:
    pass


@router.patch('/data/discovery-module-internal:schemas-info', response_model=None)
async def data_discovery_module_internal_schemas_info_patch(
    body: DataDiscoveryModuleInternalSchemasInfo,
) -> None:
    pass


@router.delete('/data/discovery-module-internal:schemas-info', response_model=None)
async def data_discovery_module_internal_schemas_info_delete() -> None:
    pass


@router.get(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}',
    response_model=DataDiscoveryModuleInternalSchemasInfoSchemasSchemasId,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_get(
    schemas_id: str = Path(..., alias='schemas-id'),
    content: Optional[Content29] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults89] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalSchemasInfoSchemasSchemasId:
    pass


@router.put(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_put(
    body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasId,
    schemas_id: str = Path(..., alias='schemas-id'),
    insert: Optional[Insert5] = 'first',
    point: Optional[str] = None,
) -> None:
    pass


@router.patch(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_patch(
    body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasId = ...,
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    pass


@router.delete(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_delete(
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    pass


@router.get(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/definition',
    response_model=DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdDefinition,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_definition_get(
    schemas_id: str = Path(..., alias='schemas-id'),
    content: Optional[Content33] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults101] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdDefinition:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')", " content: Optional[Content33] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults101] = Query('report-all'", " alias='with-defaults')"]
    definition of the schema
    """
    pass


@router.put(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/definition',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_definition_put(
    body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdDefinition = ...,
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')", ' body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdDefinition = ...']
    definition of the schema
    """
    pass


@router.patch(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/definition',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_definition_patch(
    body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdDefinition = ...,
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')", ' body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdDefinition = ...']
    definition of the schema
    """
    pass


@router.delete(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/definition',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_definition_delete(
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')"]
    definition of the schema
    """
    pass


@router.get(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/id',
    response_model=DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdId,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_id_get(
    schemas_id: str = Path(..., alias='schemas-id'),
    content: Optional[Content30] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults92] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdId:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')", " content: Optional[Content30] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults92] = Query('report-all'", " alias='with-defaults')"]
    schema id
    """
    pass


@router.put(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/id',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_id_put(
    body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdId = ...,
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')", ' body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdId = ...']
    schema id
    """
    pass


@router.patch(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/id',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_id_patch(
    body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdId = ...,
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')", ' body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdId = ...']
    schema id
    """
    pass


@router.delete(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/id',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_id_delete(
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')"]
    schema id
    """
    pass


@router.get(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/revisionCreateTime',
    response_model=DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdRevisionCreateTime,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_revision_create_time_get(
    schemas_id: str = Path(..., alias='schemas-id'),
    content: Optional[Content35] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults107] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdRevisionCreateTime:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')", " content: Optional[Content35] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults107] = Query('report-all'", " alias='with-defaults')"]
    schema revision creation time
    """
    pass


@router.put(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/revisionCreateTime',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_revision_create_time_put(
    body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdRevisionCreateTime = ...,
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')", ' body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdRevisionCreateTime = ...']
    schema revision creation time
    """
    pass


@router.patch(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/revisionCreateTime',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_revision_create_time_patch(
    body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdRevisionCreateTime = ...,
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')", ' body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdRevisionCreateTime = ...']
    schema revision creation time
    """
    pass


@router.delete(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/revisionCreateTime',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_revision_create_time_delete(
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')"]
    schema revision creation time
    """
    pass


@router.get(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/revisionId',
    response_model=DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdRevisionId,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_revision_id_get(
    schemas_id: str = Path(..., alias='schemas-id'),
    content: Optional[Content34] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults104] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdRevisionId:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')", " content: Optional[Content34] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults104] = Query('report-all'", " alias='with-defaults')"]
    Schema revision Id. Example value: 1.0
    """
    pass


@router.put(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/revisionId',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_revision_id_put(
    body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdRevisionId = ...,
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')", ' body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdRevisionId = ...']
    Schema revision Id. Example value: 1.0
    """
    pass


@router.patch(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/revisionId',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_revision_id_patch(
    body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdRevisionId = ...,
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')", ' body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdRevisionId = ...']
    Schema revision Id. Example value: 1.0
    """
    pass


@router.delete(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/revisionId',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_revision_id_delete(
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')"]
    Schema revision Id. Example value: 1.0
    """
    pass


@router.get(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/schema',
    response_model=DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdSchema,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_schema_get(
    schemas_id: str = Path(..., alias='schemas-id'),
    content: Optional[Content31] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults95] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdSchema:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')", " content: Optional[Content31] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults95] = Query('report-all'", " alias='with-defaults')"]
     schema name
    """
    pass


@router.put(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/schema',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_schema_put(
    body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdSchema = ...,
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')", ' body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdSchema = ...']
     schema name
    """
    pass


@router.patch(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/schema',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_schema_patch(
    body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdSchema = ...,
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')", ' body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdSchema = ...']
     schema name
    """
    pass


@router.delete(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/schema',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_schema_delete(
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')"]
     schema name
    """
    pass


@router.get(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/type',
    response_model=DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdType,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_type_get(
    schemas_id: str = Path(..., alias='schemas-id'),
    content: Optional[Content32] = 'config',
    depth: Optional[int] = None,
    fields: Optional[str] = None,
    filter: Optional[str] = None,
    with_defaults: Optional[WithDefaults98] = Query(
        'report-all', alias='with-defaults'
    ),
) -> DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdType:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')", " content: Optional[Content32] = 'config'", ' depth: Optional[int] = None', ' fields: Optional[str] = None', ' filter: Optional[str] = None', " with_defaults: Optional[WithDefaults98] = Query('report-all'", " alias='with-defaults')"]
    type of the schema
    """
    pass


@router.put(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/type',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_type_put(
    body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdType = ...,
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')", ' body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdType = ...']
    type of the schema
    """
    pass


@router.patch(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/type',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_type_patch(
    body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdType = ...,
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')", ' body: DataDiscoveryModuleInternalSchemasInfoSchemasSchemasIdType = ...']
    type of the schema
    """
    pass


@router.delete(
    '/data/discovery-module-internal:schemas-info/schemas={schemas_id}/type',
    response_model=None,
)
async def data_discovery_module_internal_schemas_info_schemas_schemas_id_type_delete(
    schemas_id: str = Path(..., alias='schemas-id'),
) -> None:
    """
    ['schemas_id: str = Path(...', " alias='schemas-id')"]
    type of the schema
    """
    pass
