# Routes
#
# DNS documentation:  
#
# Certificates documentation: 
#

# ssl route exemple (edge)
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.service_name }}-http
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service_name }}
spec:
  host: {{ .Values.route }}
  to:
    kind: Service
    name: {{ .Values.service_name }}
    weight: 100
  port:
    targetPort: {{ .Values.outside_pod_port }}-tcp