environments:
  develop:
  qa:
  preprod:
  master:

releases:
  - name: {{ requiredEnv "SERVICE_IMAGE_NAME" }}
    namespace: {{ requiredEnv "OCP_PROJECT" }}
    chart: ./redis
    createNamespace: false
    values:
      - ./redis.values.yaml.gotmpl