version: "3.3"
services:

  proxy:

    ports:
      - "80:80"
      - "8090:8080"




  backend:

    ports:
      - "8888:8888"

    environment:
      - PORT=8888


networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: false
